#!/bin/bash
#BSUB -P acc_untreatedIBD
#BSUB -W 48:00
#BSUB -q premium
#BSUB -J <JOB NAME>
#BSUB -n 4
#BSUB -o output_%J.stdout
#BSUB -e error_%J.sterr

# README
# this script should be executed from site of cellranger dir
# fastqs should be arranged in dirs labeled by sample
# make note not to leave trailing / in param paths
# all cluster config files (config.json, lsf.template, retry.json)
# should be present in the same location given for lsf.template

# ml cellranger parallel
ml cellranger/7.1.0

set -a

# params
PROJ_DIR=               # /path/to/proj/dir
CONFIG=$PROJ_DIR        # /path/to/config.csv
RUN_ID=                 # unique run ID
CLUST_TEMPLATE=		      # /path/to/lsf.template cluster file

################################################################################

exec >> cr_${PIPELINE}_`date '+%F_%H%M'`.log
exec 2>&1

OUT_DIR=cr_arc_${PIPELINE}_`date '+%F_%H%M'`
mkdir -p $PROJ_DIR/analysis/cellranger/$OUT_DIR && cd $_
MRO_DISK_SPACE_CHECK=disable

# core cellranger function
cellranger multi \
  --id=$RUN_ID \
  --csv=$CONFIG \
  --jobmode=$CLUST_TEMPLATE

mv $CONFIG .

# run cellranger summarizer
cd $(ls -d */ | head -n 1)
head -n 1 outs/per_sample_outs/$(ls -d */ | head -n 1)/metrics_summary.csv > ../combined_metrics.csv
cd ../
sed -i 's/^/Sample,/' combined_metrics.csv

for i in $(/bin/ls -d */); do
  PARENT_DIR=$(echo "$i" | sed 's/\///g')  # Extract the parent subdirectory name
  for j in "$i"outs/per_sample_outs/*/; do
    SUBSUB_DIR=$(echo "$j" | sed -e 's/\/outs\///g' -e 's/\///g')  # Extract the sub-subdirectory name
    METRICS=$(tail -n 1 "${j}outs/metrics_summary.csv")
    LABEL="${PARENT_DIR}_${SUBSUB_DIR}"
    echo "${LABEL},${METRICS}" >> combined_metrics.csv
  done
done

