#!/bin/bash
#BSUB -J cr_vdj-b
#BSUB -P acc_untreatedIBD
#BSUB -W 02:00
#BSUB -q express
#BSUB -n 2
#BSUB -R rusage[mem=64GB]
#BSUB -R span[hosts=1]
#BSUB -o ../logs/output_%J.stdout
#BSUB -eo ../logs/error_%J.stderr
#BSUB -L /bin/bash

# params
COUNT=8                 # number of samples
PROJ_DIR=/hpc/users/tastac01/ctastad/projects/conv_covid_seq
REF_DIR=/hpc/users/tastac01/ctastad/ref_genomes/10x
GENE_REF=refdata-cellranger-vdj-GRCh38-alts-ensembl-5.0.0
ANALYSIS_OUT=$PROJ_DIR/analysis/cr_vdj_`date '+%F_%H%M'`
SAMPLE_DIR=$PROJ_DIR/data/fastqs
SAMPLE=TD005310-CP-1-BCR,TD005310-CP-1-TCR

################################################################################

module load cellranger parallel
mkdir $ANALYSIS_OUT && cd $_

# core cellranger function
cellranger vdj \
  --id=cr_vdj_`date '+%F_%H%M'` \
  --reference=$REF_DIR/$GENE_REF \
  --fastqs=$SAMPLE_DIR \
  --sample=$SAMPLE

