#!/bin/bash
#BSUB -J cr_count
#BSUB -P acc_untreatedIBD
#BSUB -W 02:00
#BSUB -q express
#BSUB -n 2
#BSUB -R rusage[mem=64GB]
#BSUB -R span[hosts=1]
#BSUB -o ../logs/output_%J.stdout
#BSUB -eo ../logs/error_%J.stderr
#BSUB -L /bin/bash

# this script should be executed from site of output dir
# fastqs should be arranged in dirs arranged by sample
# dirs should carry sample name

# params
PIPELINE=               # name of cr pipeline
PROJ_DIR=               # /path/to/proj/dir
REF_DIR=                # /path/to/gene/refs
GENE_REF=               # name of gene ref
SAMPLE_DIR=$PROJ_DIR/   # /proj/subdir/to/fastqs

################################################################################

module load cellranger

# needed because pipelines differe for name of reference genome
if [[ $PIPELINE == "count" ]]
then
    GENOME_LABEL=transcriptome
else
    GENOME_LABEL=reference
fi

# core cellranger function
for i in $SAMPLE_DIR/*
do
cellranger $PIPELINE \
  --id=cr_${PIPELINE}_${i##*/}_`date '+%F_%H%M'` \
  --$GENOME_LABEL=$REF_DIR/$GENE_REF \
  --fastqs=$SAMPLE_DIR/${i##*/} \
  --sample=${i##*/}
done

