#!/bin/bash
#BSUB -J cr_count
#BSUB -P acc_untreatedIBD
#BSUB -W 02:00
#BSUB -q express
#BSUB -n 2
#BSUB -R rusage[mem=64GB]
#BSUB -R span[hosts=1]
#BSUB -o ../logs/output_%J.stdout
#BSUB -eo ../logs/error_%J.stderr
#BSUB -L /bin/bash

# README
# this script should be executed from site of output dir
# fastqs should be arranged in dirs labeled by sample
# make note not to leave trailing / in param paths

set -a

# params
PIPELINE=			        # name of cellranger pipeline
PROJ_DIR=			        # /path/to/proj/dir
REF_DIR=			        # /path/to/gene/ref
GENE_REF=			        # name of gene ref
LIBS=					# /path/to/libraries.csv

################################################################################

OUT_DIR=cr_atac_${PIPELINE}_`date '+%F_%H%M'`
mkdir -p $PROJ_DIR/analysis/cellranger/$OUT_DIR
cd $PROJ_DIR/analysis/cellranger/$OUT_DIR

# core cellranger function
cellranger-arc $PIPELINE \
    --id=$OUT_DIR \
    --reference=$REF_DIR/$GENE_REF \
    --libraries=$LIBS

# cellranger function run with gnuparallel
# parallel crProcess ::: $(ls $SAMPLE_DIR)

