#!/bin/bash
#BSUB -J cr_count
#BSUB -P acc_untreatedIBD
#BSUB -W 02:00
#BSUB -q express
#BSUB -n 2
#BSUB -R rusage[mem=64GB]
#BSUB -R span[hosts=1]
#BSUB -o ../logs/output_%J.stdout
#BSUB -eo ../logs/error_%J.stderr
#BSUB -L /bin/bash

# number of samples
COUNT=8 	
REF_DIR=/hpc/users/tastac01/ctastad/ref_genomes/10x
GENE_REF=refdata-gex-GRCh38-2020-A
ANALYSIS_OUT=/hpc/users/tastac01/ctastad/projects/conv_covid_seq/analysis
SAMPLE_DIR=/hpc/users/tastac01/ctastad/projects/conv_covid_seq/data/fastqs

module load cellranger parallel
mkdir $ANALYSIS_OUT/cr_count_`date '+%F_%H%M'` && cd $_

# core cellranger function
cr_count () {
  cellranger count \
    --id=cr_count_$1_`date '+%F_%H%M'` \
    --transcriptome=$REF_DIR/$GENE_REF \
    --fastqs=$SAMPLE_DIR \
    --sample=$1-GEX \
}

# export cr function to env for parallel
export -f cr_count	

# execute cellranger in parallel
find TD005310-CP-* | cut -d. -f1 | parallel cr_count {}
