#!/bin/bash
#BSUB -J cr_count
#BSUB -P acc_untreatedIBD
#BSUB -W 02:00
#BSUB -q express
#BSUB -n 2
#BSUB -R rusage[mem=64GB]
#BSUB -R span[hosts=1]
#BSUB -o ../logs/output_%J.stdout
#BSUB -eo ../logs/error_%J.stderr
#BSUB -L /bin/bash

# this script should be executed from site of output dir
# fastqs should be arranged in dirs arranged by sample
# dirs should carry sample name

set -a

# params
PIPELINE=			# name of cellranger pipeline
PROJ_DIR=			# /path/to/proj/dir
REF_DIR=			# /path/to/gene/ref
GENE_REF=			# name of gene ref
SAMPLE_DIR=$PROJ_DIR/		# /proj/subdir/to/fastqs
CELLS=				# expected cell count
CHEM=				# chemistry type (e.g. fiveprime)

################################################################################

# needed because pipelines differ for name of reference genome
if [[ $PIPELINE == "count" ]]
then
    GENOME_LABEL=transcriptome
else
    GENOME_LABEL=reference
fi

# core cellranger function
crProcess () {
cellranger $PIPELINE \
  --id=cr_${PIPELINE}_${1}_`date '+%F_%H%M'` \
  --$GENOME_LABEL=$REF_DIR/$GENE_REF \
  --fastqs=$SAMPLE_DIR/$1 \
  --sample=$1 \
  --expect-cells=$CELLS \
  --chemistry=$CHEM
}
#done

export -f crProcess

# cellranger function run with gnuparallel
parallel crProcess ::: $(ls $SAMPLE_DIR)

