#!/bin/bash
#BSUB -J coresc
#BSUB -P acc_untreatedIBD
#BSUB -W 01:00
#BSUB -q premium
#BSUB -n 12
#BSUB -R span[hosts=1]
#BSUB -R rusage[mem=12000]
#BSUB -u christopher.tastad@mssm.edu
#BSUB -o output_%J.stdout
#BSUB -eo error_%J.stderr
#BSUB -L /bin/bash

# README
# This script should be executed from the site of the output dir

PROJ_DIR=                   # project directory
CORESC_DIR=$PROJ_DIR                   # coreSC directory
ATAC=FALSE                  # run atac-multi-wnn routine
CITE=FALSE                  # run cite-wnn routine
HARMONIZE=FALSE             # run harmony integration
VERSION=                    # seurat version to use i.e. v4-r2

################################################################################

export http_proxy=http://172.28.7.1:3128
export https_proxy=http://172.28.7.1:3128
export all_proxy=http://172.28.7.1:3128
export no_proxy=localhost,*.chimera.hpc.mssm.edu,172.28.0.0/16

cd $CORESC_DIR

ml singularity

./run -v $VERSION -a $ATAC -c $CITE -h $HARMONIZE

