#!/bin/bash
#BSUB -J nextflow
#BSUB -P acc_untreatedIBD
#BSUB -W 08:00
#BSUB -q premium
#BSUB -n 24
#BSUB -R span[ptile=12]
#BSUB -R rusage[mem=36000]
#BSUB -u christopher.tastad@mssm.edu
#BSUB -o output_%J.stdout
#BSUB -eo error_%J.stderr
#BSUB -L /bin/bash

# README
# This script should be executed at the site of the output dir

PROJ_DIR=			# project directory
NFC_PIPE=			# nf-core pipeline - e.g. nf-core/rnaseq
NFC_VER=			# nf-core pipeline version
NFC_PROFILE=singularity		# nf-core profile (singularity req'd on minerva)
SAMPLESHEET=			# sample input
OUTDIR=				# output directory location
GENOME=				# reference genome

################################################################################

export http_proxy=http://172.28.7.1:3128
export https_proxy=http://172.28.7.1:3128
export all_proxy=http://172.28.7.1:3128
export no_proxy=localhost,*.chimera.hpc.mssm.edu,172.28.0.0/16

ml java
ml anaconda3
ml singularity

source $CONDA_PREFIX/etc/profile.d/conda.sh
conda init bash
conda activate nextflow

cd $PROJ_DIR 

nextflow run $NFC_PIPE \
	-r $NFC_VER \
	-profile $NFC_PROFILE \
	-w /sc/arion/scratch/$USER/work \
	--input $SAMPLESHEET \
	--outdir $OUTDIR \
	--genome $GENOME

