#!/bin/bash
#BSUB -J nextflow
#BSUB -P acc_untreatedIBD
#BSUB -W 08:00
#BSUB -q express
#BSUB -n 96
#BSUB -R span[ptile=12]
#BSUB -R rusage[mem=8000]
#BSUB -u christopher.tastad@mssm.edu
#BSUB -o output_%J.stdout
#BSUB -eo error_%J.stderr
#BSUB -L /bin/bash

# README
# This script should be executed at the site of the output dir

export http_proxy=http://172.28.7.1:3128
export https_proxy=http://172.28.7.1:3128
export all_proxy=http://172.28.7.1:3128
export no_proxy=localhost,*.chimera.hpc.mssm.edu,172.28.0.0/16

ml java
ml anaconda3
ml singularity

source $CONDA_PREFIX/etc/profile.d/conda.sh
conda init bash
conda activate nextflow

---

cd /hpc/users/tastac01/ctastad/projects/crispr-screening/analysis/rnaseq

nextflow run nf-core/rnaseq \
	-r 3.10.1 \
	-profile singularity \
	--input 2022-01-11_30-757740164_samplesheet.csv \
	--outdir 2022-01-11_30-757740164 \
	--genome GRCh38

