[tool.black]
line-length = 80
string-normalization = true
preview = true

[tool.isort]
profile = "black"
line_length = 80
wrap_length = 80
multi_line_output = 3
include_trailing_comma = true

[tool.flake8]
max-line-length = 80
max-doc-length = 72
extend-ignore = ["E501"]
docstring-convention = "google"
