#!/bin/bash
#BSUB -J cr_multi
#BSUB -P acc_untreatedIBD
#BSUB -W 04:00
#BSUB -q express
#BSUB -n 2
#BSUB -R rusage[mem=64GB]
#BSUB -R span[hosts=1]
#BSUB -o ../logs/output_%J.stdout
#BSUB -eo ../logs/error_%J.stderr
#BSUB -L /bin/bash

# params
COUNT=8 		# number of samples
PROJ_DIR=/hpc/users/tastac01/ctastad/projects/conv_covid_seq
REF_DIR=/hpc/users/tastac01/ctastad/ref_genomes/10x
GENE_REF=refdata-gex-GRCh38-2020-A
ANALYSIS_OUT=$PROJ_DIR/analysis/cr_multi_`date '+%F_%H%M'`
SAMPLE_DIR=$PROJ_DIR/data/fastqs
CONFIG_DIR=$PROJ_DIR/analysis

################################################################################

module load cellranger parallel
mkdir $ANALYSIS_OUT && cd $_

# core cellranger function
cr_multi () {
  cellranger multi \
    --id=cr_multi_$1_`date '+%F_%H%M'` \
    --csv=$1.csv
}

# export cr function to env for parallel
export -f cr_multi

# iterate through generation of config csv per sample
for i in $(seq 1 $COUNT); do
  cp $CONFIG_DIR/cellranger_multi_config_template.csv $ANALYSIS_OUT/TD005310-CP-$i.csv
  sed -i -e "s/\*\*\*/$i/g" TD005310-CP-$i.csv
done

# execute cellranger in parallel
find TD005310-CP-* | cut -d. -f1 | parallel cr_multi {}

