#!/bin/bash
#BSUB -J job_of_chris
#BSUB -P acc_untreatedIBD
#BSUB -W 01:00
#BSUB -q express
#BSUB -n 96
#BSUB -R span[ptile=12]
#BSUB -R rusage[mem=8000]
#BSUB -u christopher.tastad@mssm.edu
#BSUB -o /hpc/users/tastac01/ctastad/logs/output_%J.stdout
#BSUB -eo /hpc/users/tastac01/ctastad/logs/error_%J.stderr
#BSUB -L /bin/bash

export http_proxy=http://172.28.7.1:3128
export https_proxy=http://172.28.7.1:3128
export all_proxy=http://172.28.7.1:3128
export no_proxy=localhost,*.chimera.hpc.mssm.edu,172.28.0.0/16

ml java
ml anaconda3
ml singularity

source $CONDA_PREFIX/etc/profile.d/conda.sh
conda init bash
conda activate nextflow
cd /hpc/users/tastac01/ctastad/projects/crispr-screening/analysis/rnaseq/test

nextflow run nf-core/rnaseq -r 3.10.1 -profile test,singularity --outdir .

